### PR TITLE
fix wcsncmp in script-engine

### PR DESCRIPTION
**Pull request by xmaple555**
# Description

https://github.com/HyperDbg/HyperDbg/issues/373

image

image

The parsr would parse space as token.

BTW, I recently finish my compiler couerse, and learn a lot about compiler knowledge, so I believe there are a lot of things we can modify and improve for the parser, like it is better that not define the grammer for each different functions , this way would make more complited to define new functions .

### CODE REVIEW

**Comment by SinaKarvandi** [comment]
> The parsr would parse space as token.
> 
> BTW, I recently finish my compiler couerse, and learn a lot about compiler knowledge, so I believe there are a lot of things we can modify and improve for the parser, like it is better that not define the grammer for each different functions , this way would make more complited to define new functions .

That's great I'm also trying to port the script engine evaluation engine for hardware debugging: https://github.com/HyperDbg/HyperDbg/blob/master/hwdbg/src/main/scala/hwdbg/script/eval.scala

Soon, the scripts will also be able to run directly on hardware debugger (hwdbg).

**Comment by SinaKarvandi** [comment]
The patch doesn't seem to work. 

I added the following commit to support your modifications:
https://github.com/HyperDbg/HyperDbg/commit/f5d7332a195cb1b34f19a87b858163e565af2413

Mainly added this function:
image

and this check:
image

But when I test the new `wcsncmp` function, it has some weird behavior, it doesn't show the `printf` results on this script:

```
? printf("process name: %d\n", wcscmp(L"hyperdbg-cli.exe", L"hyperdbg-cli.e"));

? printf("process name: %d\n", wcsncmp(L"hyperdbg-cli.exe", L"hyperdbg-cli.e", 0n5));

```

The first script that uses the `wcscmp` is pretty fine but the second script that uses the `wcsncmp` doesn't show the process name. It seems that the stack of the tokens is not correctly configured:

image


Am I making incorrect modifications?

**Comment by xmaple555** [comment]
well, I can fix later. Please commit the current code to branch script .

**Comment by SinaKarvandi** [comment]
Great! I made a branch for it: https://github.com/HyperDbg/HyperDbg/tree/script

**Pull request merged**
