### PR TITLE
fix lnk 2019

### PR DESCRIPTION
**Pull request by botao1995**

### CODE REVIEW

**Comment by botao1995** [comment]
Can we implement similar functions of enumeration process, such as a in WinDbg !process 0 0

**Comment by SinaKarvandi** [comment]
Yes, of course. But in developing these things, we should keep in mind that all EPROCESS(s) should be located on non-paged pool memory. Otherwise, the command might not be stable.

**Comment by botao1995** [comment]
> Yes, of course. But in developing these things, we should keep in mind that all EPROCESS(s) should be located on non-paged pool memory. Otherwise, the command might not be stable.
ok,You may not understand what I mean. Is there a command like WinDbg in this project to enumerate all processes, such as (! process 0 0）

**Comment by botao1995** [comment]
> Yes, of course. But in developing these things, we should keep in mind that all EPROCESS(s) should be located on non-paged pool memory. Otherwise, the command might not be stable.

And can you set symbols like WinDbg

**Comment by SinaKarvandi** [comment]
Yeah, symbols are not fully implemented yet but you can use symbols too.
E.g., in the x command.
https://docs.hyperdbg.com/commands/debugging-commands/x

**Comment by botao1995** [comment]
> Yeah, symbols are not fully implemented yet but you can use symbols too.
> E.g., in the x command.
> https://docs.hyperdbg.com/commands/debugging-commands/x

Can hyperdbg enumerate process lists?

**Comment by SinaKarvandi** [comment]
Not yet.

**Comment by botao1995** [comment]
> Not yet.

This function can be considered in addition to getting better functions of WinDbg

**Comment by SinaKarvandi** [comment]
Sure, we'll add it soon.

**Comment by botao1995** [comment]
> Sure, we'll add it soon.

好的，谢谢，thank you.

**Comment by botao1995** [comment]
> Sure, we'll add it soon.



> Sure, we'll add it soon.

Do you have wechat? I can ask you if you have any questions,

Chinese mainland can not use Twitter

**Comment by SinaKarvandi** [comment]
No, I don't have WeChat. But you can join the group on Telegram: https://t.me/HyperDbg

**Comment by botao1995** [comment]
> No, I don't have WeChat. But you can join the group on Telegram: https://t.me/HyperDbg

Joined，thank you.

**Pull request merged**
