### PR TITLE
Fix bug that had one more page

### PR DESCRIPTION
**Pull request by gmh5225**
Fix bug that had one more page

### CODE REVIEW

**Comment by SinaKarvandi** [comment]
Hi,
Thanks for creating the PR.

It seems to be incorrect. Assume the following scenario :

```
PageCount = 5;

i = 0; => ReadSize = (UINT64)PAGE_ALIGN(AddressToRead + PAGE_SIZE) - AddressToRead;
i = 1; => ReadSize = PAGE_SIZE;
i = 2; => ReadSize = PAGE_SIZE;
i = 3; => ReadSize = PAGE_SIZE;
i = 4; => ReadSize = PAGE_SIZE;
i = 5; => ReadSize = SizeToRead;

-----------------------------------------------------------------

PageCount = 5;

i = 0; => ReadSize = (UINT64)PAGE_ALIGN(AddressToRead + PAGE_SIZE) - AddressToRead;
i = 1; => ReadSize = PAGE_SIZE;
i = 2; => ReadSize = PAGE_SIZE;
i = 3; => ReadSize = PAGE_SIZE;
i = 4; => ReadSize = SizeToRead;
```

These two scenarios aren't equal. You've missed a page read on the second scenario.

Am I right?

**Comment by gmh5225** [comment]
you set `UINT64 PageCount = SizeToRead / PAGE_SIZE + 1;`

when `SizeToRead = 0x1001` -> `PageCount = 0x1001 / 0x1000 + 1 = 2`

then you set `for (size_t i = 0; i <= PageCount; i++)`
```
i = 0; => ReadSize = (UINT64)PAGE_ALIGN(AddressToRead + PAGE_SIZE) - AddressToRead;
i = 1; => ReadSize = PAGE_SIZE;
i = 2; => ReadSize = SizeToRead;
```
this reads 3 pages, but we actually want to read 2 page.

when `SizeToRead = 0x2000` -> `PageCount = 0x2000 / 0x1000 + 1 = 3`

then you set `for (size_t i = 0; i <= PageCount; i++)`
```
i = 0; => ReadSize = (UINT64)PAGE_ALIGN(AddressToRead + PAGE_SIZE) - AddressToRead;
i = 1; => ReadSize = PAGE_SIZE;
i = 2; => ReadSize = PAGE_SIZE;
i = 3; => ReadSize = SizeToRead;
```
this reads 4 pages, but we actually want to read 2 page.

**Comment by SinaKarvandi** [comment]
It's not about the size; it's about the location of the address that may reside on 3 pages. Imagine we want to read 0x1500 bytes from memory. Should we access 2 pages? No, not always.

Assume our address is 0x10001f00 (0x10001f00 + 0x1500 = 0x10003400).

In this address : 
Page 1                                              Page 2                                             Page 3
0x100 Bytes                                  |    0x1000                                        |     0x400
0x10001f00 ... 0x10002000           |  0x10002000 ... 0x10003000          |  0x10003000 ... 0x10003400 

As you can see, we need 3-page accesses to read 0x1500 bytes, not two.

Does it seem right?

**Comment by SinaKarvandi** [comment]
Yep, it seems you're right about the 0x2000. The code doesn't work for these cases. However, your solution seems to have problems too. I wrote some user-mode codes for further investigation:


```
#include <Windows.h>
#include <conio.h>
#include <iostream>

#define PAGE_SIZE 0x1000
#define PAGE_ALIGN(Va) ((PVOID)((ULONG_PTR)(Va) & ~(PAGE_SIZE - 1)))

int main() {

  UINT64 AddressToRead = 0x10001f00;
  UINT64 SizeToRead = 0x1500;

  //
  // Check whether we should apply multiple accesses or not
  //
  UINT64 AddressToCheck =
      (CHAR *)AddressToRead + SizeToRead - ((CHAR *)PAGE_ALIGN(AddressToRead));

  if (AddressToCheck > PAGE_SIZE) {
    //
    // Address should be accessed in more than one page
    //
    UINT64 PageCount = SizeToRead / PAGE_SIZE + 1;

    for (size_t i = 0; i < PageCount; i++) {
      UINT64 ReadSize = 0;

      if (i == 0) {
        ReadSize =
            (UINT64)PAGE_ALIGN(AddressToRead + PAGE_SIZE) - AddressToRead;
      } else if (i == PageCount -1) {
        ReadSize = SizeToRead;
      } else {
        ReadSize = PAGE_SIZE;
      }

      printf("Addr From : %llx to Addr To : %llx | ReadSize : %llx\n",
             AddressToRead, AddressToRead + ReadSize, ReadSize);

      //
      // Apply the changes to the next addresses (if any)
      //
      SizeToRead = SizeToRead - ReadSize;
      AddressToRead = AddressToRead + ReadSize;
    }
  }

  _getch();
}
```

**Comment by SinaKarvandi** [comment]
The result of modifications for this commit is : 
image

**Comment by gmh5225** [comment]
Oh..yes.
I hadn't considered the situation that reside on 3 pages.

**Comment by SinaKarvandi** [comment]
Do you agree with this solution: 

```
#include <Windows.h>
#include <conio.h>
#include <iostream>

#define PAGE_SIZE 0x1000
#define PAGE_ALIGN(Va) ((PVOID)((ULONG_PTR)(Va) & ~(PAGE_SIZE - 1)))

int main() {

  UINT64 AddressToRead = 0x10001f00;
  UINT64 SizeToRead = 0x1500;

  /*
UINT64 AddressToRead = 0x10002000;
UINT64 SizeToRead = 0x2000;
*/
  //
  // Check whether we should apply multiple accesses or not
  //
  UINT64 AddressToCheck =
      (CHAR *)AddressToRead + SizeToRead - ((CHAR *)PAGE_ALIGN(AddressToRead));

  if (AddressToCheck > PAGE_SIZE) {
    //
    // Address should be accessed in more than one page
    //
    UINT64 PageCount = SizeToRead / PAGE_SIZE + 1;

    if (SizeToRead % PAGE_SIZE == 0) {
      PageCount -= 1;
    }

    for (size_t i = 0; i <= PageCount; i++) {
      UINT64 ReadSize = 0;

      if (i == 0) {
        ReadSize =
            (UINT64)PAGE_ALIGN(AddressToRead + PAGE_SIZE) - AddressToRead;
      } else if (i == PageCount) {
        ReadSize = SizeToRead;

        if (ReadSize == 0) {
          break;
        }
      } else {
        ReadSize = PAGE_SIZE;
      }

      printf("Addr From : %llx to Addr To : %llx | ReadSize : %llx\n",
             AddressToRead, AddressToRead + ReadSize, ReadSize);

      //
      // Apply the changes to the next addresses (if any)
      //
      SizeToRead = SizeToRead - ReadSize;
      AddressToRead = AddressToRead + ReadSize;
    }
  }

  _getch();
}
```

**Comment by gmh5225** [comment]
there will still be problems
the following code will cause a memory overflow
```
auto ReadBuffer = malloc(0x2000);
RPM(ReadBuffer, 0x2000, TargetAddress);
```
we have only allocated 0x2000 size, but `PageCount = 3`

**Comment by SinaKarvandi** [comment]
No, the following line breaks the loop at the third iteration:

```
        if (ReadSize == 0) {
          break;
        }
```

**Comment by gmh5225** [comment]
No, the following code result is 3 pages
```
#include <Windows.h>
#include <conio.h>
#include <iostream>

#define PAGE_SIZE 0x1000
#define PAGE_ALIGN(Va) ((PVOID)((ULONG_PTR)(Va) & ~(PAGE_SIZE - 1)))

int main() {

	UINT64 AddressToRead = 0xFFFFF80758050020;
	UINT64 SizeToRead = 0x2000;


	//UINT64 AddressToRead = 0x10002000;
	//UINT64 SizeToRead = 0x2000;

	//
	// Check whether we should apply multiple accesses or not
	//
	UINT64 AddressToCheck =
		(CHAR*)AddressToRead + SizeToRead - ((CHAR*)PAGE_ALIGN(AddressToRead));

	if (AddressToCheck > PAGE_SIZE) {
		//
		// Address should be accessed in more than one page
		//
		UINT64 PageCount = SizeToRead / PAGE_SIZE + 1;

		if (SizeToRead % PAGE_SIZE == 0) {
			PageCount -= 1;
		}

		for (size_t i = 0; i <= PageCount; i++) {
			UINT64 ReadSize = 0;

			if (i == 0) {
				ReadSize =
					(UINT64)PAGE_ALIGN(AddressToRead + PAGE_SIZE) - AddressToRead;
			}
			else if (i == PageCount) {
				ReadSize = SizeToRead;

				if (ReadSize == 0) {
					break;
				}
			}
			else {
				ReadSize = PAGE_SIZE;
			}

			printf("Addr From : %llx to Addr To : %llx | ReadSize : %llx\n",
				AddressToRead, AddressToRead + ReadSize, ReadSize);

			//
			// Apply the changes to the next addresses (if any)
			//
			SizeToRead = SizeToRead - ReadSize;
			AddressToRead = AddressToRead + ReadSize;
		}
	}

	_getch();
}
```
->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```
Addr From : fffff80758050020 to Addr To : fffff80758051000 | ReadSize : fe0
Addr From : fffff80758051000 to Addr To : fffff80758052000 | ReadSize : 1000
Addr From : fffff80758052000 to Addr To : fffff80758052020 | ReadSize : 20
```

**Comment by gmh5225** [comment]
I have added `TempReadBuffer`to avoid memory overflow
[Add TempReadBuffer to avoid memory overflow](https://github.com/HyperDbg/HyperDbg/pull/171/commits/7c59a3453a4be28bafe7ce8d2f2fae4b4edf7d99)

 I don't have a good solution for memory writes now.
 Do you have any good ideas for a solution?

**Comment by SinaKarvandi** [comment]
No, the last solution is entirely wrong! We're not allowed to use ExAllocatePoolWithTag in this function. It is supposed to be called in the vmx-root mode, so as paging is not available at vmx-root, then using ExAllocatePoolWithTag is not allowed.

**Comment by SinaKarvandi** [comment]
> No, the result of following code is 3 pages
> 
> ```c++
> #include <Windows.h>
> #include <conio.h>
> #include <iostream>
> 
> #define PAGE_SIZE 0x1000
> #define PAGE_ALIGN(Va) ((PVOID)((ULONG_PTR)(Va) & ~(PAGE_SIZE - 1)))
> 
> int main() {
> 
> 	UINT64 AddressToRead = 0xFFFFF80758050020;
> 	UINT64 SizeToRead = 0x2000;
> 
> 
> 	//UINT64 AddressToRead = 0x10002000;
> 	//UINT64 SizeToRead = 0x2000;
> 
> 	//
> 	// Check whether we should apply multiple accesses or not
> 	//
> 	UINT64 AddressToCheck =
> 		(CHAR*)AddressToRead + SizeToRead - ((CHAR*)PAGE_ALIGN(AddressToRead));
> 
> 	if (AddressToCheck > PAGE_SIZE) {
> 		//
> 		// Address should be accessed in more than one page
> 		//
> 		UINT64 PageCount = SizeToRead / PAGE_SIZE + 1;
> 
> 		if (SizeToRead % PAGE_SIZE == 0) {
> 			PageCount -= 1;
> 		}
> 
> 		for (size_t i = 0; i <= PageCount; i++) {
> 			UINT64 ReadSize = 0;
> 
> 			if (i == 0) {
> 				ReadSize =
> 					(UINT64)PAGE_ALIGN(AddressToRead + PAGE_SIZE) - AddressToRead;
> 			}
> 			else if (i == PageCount) {
> 				ReadSize = SizeToRead;
> 
> 				if (ReadSize == 0) {
> 					break;
> 				}
> 			}
> 			else {
> 				ReadSize = PAGE_SIZE;
> 			}
> 
> 			printf("Addr From : %llx to Addr To : %llx | ReadSize : %llx\n",
> 				AddressToRead, AddressToRead + ReadSize, ReadSize);
> 
> 			//
> 			// Apply the changes to the next addresses (if any)
> 			//
> 			SizeToRead = SizeToRead - ReadSize;
> 			AddressToRead = AddressToRead + ReadSize;
> 		}
> 	}
> 
> 	_getch();
> }
> ```
> 
> ->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 
> ```
> Addr From : fffff80758050020 to Addr To : fffff80758051000 | ReadSize : fe0
> Addr From : fffff80758051000 to Addr To : fffff80758052000 | ReadSize : 1000
> Addr From : fffff80758052000 to Addr To : fffff80758052020 | ReadSize : 20
> ```

Yes, it's correct; we should have 3 page accesses in this case. We're accessing memory on 3 different pages.

**Comment by SinaKarvandi** [comment]
Okay, here is a final solution (more straightforward solution) that probably covers all the cases correctly.
Please test it and tell me if you can break its semantics with any test cases.

```
#include <Windows.h>
#include <conio.h>
#include <iostream>

#define PAGE_SIZE 0x1000
#define PAGE_ALIGN(Va) ((PVOID)((ULONG_PTR)(Va) & ~(PAGE_SIZE - 1)))

int main() {

  UINT64 AddressToRead = 0x10001f00;
  UINT64 SizeToRead = 0x5500;

  // UINT64 AddressToRead = 0x10001f00;
  // UINT64 SizeToRead = 0x1500;

  // UINT64 AddressToRead = 0x10002000;
  // UINT64 SizeToRead = 0x1001;

  // UINT64 AddressToRead = 0x10002000;
  // UINT64 SizeToRead = 0x2000;

  // UINT64 AddressToRead = 0x10001f00;
  // UINT64 SizeToRead = 0x1001;

  // UINT64 AddressToRead = 0x10001f00;
  // UINT64 SizeToRead = 0x501;

  //
  // Check whether we should apply multiple accesses or not
  //
  UINT64 AddressToCheck =
      (CHAR *)AddressToRead + SizeToRead - ((CHAR *)PAGE_ALIGN(AddressToRead));

  if (AddressToCheck > PAGE_SIZE) {
    //
    // Address should be accessed in more than one page
    //
    UINT64 ReadSize = AddressToCheck;

    while (SizeToRead != 0) {

      ReadSize = (UINT64)PAGE_ALIGN(AddressToRead + PAGE_SIZE) - AddressToRead;

      if (ReadSize == PAGE_SIZE && SizeToRead < PAGE_SIZE) {
        ReadSize = SizeToRead;
      }

      printf("Addr From : %llx to Addr To : %llx | ReadSize : %llx\n",
             AddressToRead, AddressToRead + ReadSize, ReadSize);

      //
      // Apply the changes to the next addresses (if any)
      //
      SizeToRead = SizeToRead - ReadSize;
      AddressToRead = AddressToRead + ReadSize;
    }
  }

  _getch();
}
```

**Comment by gmh5225** [comment]
> No, the last solution is entirely wrong! We're not allowed to use ExAllocatePoolWithTag in this function. It is supposed to be called in the vmx-root mode, so as paging is not available at vmx-root, then using ExAllocatePoolWithTag is not allowed.

Oh..sorry. 
my bad, I didn't think about vmx-root

**Comment by gmh5225** [comment]
> Okay, here is a final solution (more straightforward solution) that probably covers all the cases correctly. Please test it and tell me if you can break its semantics with any test cases.
> 
> ```
> #include <Windows.h>
> #include <conio.h>
> #include <iostream>
> 
> #define PAGE_SIZE 0x1000
> #define PAGE_ALIGN(Va) ((PVOID)((ULONG_PTR)(Va) & ~(PAGE_SIZE - 1)))
> 
> int main() {
> 
>   UINT64 AddressToRead = 0x10001f00;
>   UINT64 SizeToRead = 0x5500;
> 
>   // UINT64 AddressToRead = 0x10001f00;
>   // UINT64 SizeToRead = 0x1500;
> 
>   // UINT64 AddressToRead = 0x10002000;
>   // UINT64 SizeToRead = 0x1001;
> 
>   // UINT64 AddressToRead = 0x10002000;
>   // UINT64 SizeToRead = 0x2000;
> 
>   // UINT64 AddressToRead = 0x10001f00;
>   // UINT64 SizeToRead = 0x1001;
> 
>   // UINT64 AddressToRead = 0x10001f00;
>   // UINT64 SizeToRead = 0x501;
> 
>   //
>   // Check whether we should apply multiple accesses or not
>   //
>   UINT64 AddressToCheck =
>       (CHAR *)AddressToRead + SizeToRead - ((CHAR *)PAGE_ALIGN(AddressToRead));
> 
>   if (AddressToCheck > PAGE_SIZE) {
>     //
>     // Address should be accessed in more than one page
>     //
>     UINT64 ReadSize = AddressToCheck;
> 
>     while (SizeToRead != 0) {
> 
>       ReadSize = (UINT64)PAGE_ALIGN(AddressToRead + PAGE_SIZE) - AddressToRead;
> 
>       if (ReadSize == PAGE_SIZE && SizeToRead < PAGE_SIZE) {
>         ReadSize = SizeToRead;
>       }
> 
>       printf("Addr From : %llx to Addr To : %llx | ReadSize : %llx\n",
>              AddressToRead, AddressToRead + ReadSize, ReadSize);
> 
>       //
>       // Apply the changes to the next addresses (if any)
>       //
>       SizeToRead = SizeToRead - ReadSize;
>       AddressToRead = AddressToRead + ReadSize;
>     }
>   }
> 
>   _getch();
> }
> ```
Nice work.
the final solution worked for me  :)

**Comment by gmh5225** [comment]
> 
Yes. Actually 3 pages need to be read. I thought wrong before.

**Comment by gmh5225** [comment]
> > No, the result of following code is 3 pages
> > ```c++
> > #include <Windows.h>
> > #include <conio.h>
> > #include <iostream>
> > 
> > #define PAGE_SIZE 0x1000
> > #define PAGE_ALIGN(Va) ((PVOID)((ULONG_PTR)(Va) & ~(PAGE_SIZE - 1)))
> > 
> > int main() {
> > 
> > 	UINT64 AddressToRead = 0xFFFFF80758050020;
> > 	UINT64 SizeToRead = 0x2000;
> > 
> > 
> > 	//UINT64 AddressToRead = 0x10002000;
> > 	//UINT64 SizeToRead = 0x2000;
> > 
> > 	//
> > 	// Check whether we should apply multiple accesses or not
> > 	//
> > 	UINT64 AddressToCheck =
> > 		(CHAR*)AddressToRead + SizeToRead - ((CHAR*)PAGE_ALIGN(AddressToRead));
> > 
> > 	if (AddressToCheck > PAGE_SIZE) {
> > 		//
> > 		// Address should be accessed in more than one page
> > 		//
> > 		UINT64 PageCount = SizeToRead / PAGE_SIZE + 1;
> > 
> > 		if (SizeToRead % PAGE_SIZE == 0) {
> > 			PageCount -= 1;
> > 		}
> > 
> > 		for (size_t i = 0; i <= PageCount; i++) {
> > 			UINT64 ReadSize = 0;
> > 
> > 			if (i == 0) {
> > 				ReadSize =
> > 					(UINT64)PAGE_ALIGN(AddressToRead + PAGE_SIZE) - AddressToRead;
> > 			}
> > 			else if (i == PageCount) {
> > 				ReadSize = SizeToRead;
> > 
> > 				if (ReadSize == 0) {
> > 					break;
> > 				}
> > 			}
> > 			else {
> > 				ReadSize = PAGE_SIZE;
> > 			}
> > 
> > 			printf("Addr From : %llx to Addr To : %llx | ReadSize : %llx\n",
> > 				AddressToRead, AddressToRead + ReadSize, ReadSize);
> > 
> > 			//
> > 			// Apply the changes to the next addresses (if any)
> > 			//
> > 			SizeToRead = SizeToRead - ReadSize;
> > 			AddressToRead = AddressToRead + ReadSize;
> > 		}
> > 	}
> > 
> > 	_getch();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> > ```
> > Addr From : fffff80758050020 to Addr To : fffff80758051000 | ReadSize : fe0
> > Addr From : fffff80758051000 to Addr To : fffff80758052000 | ReadSize : 1000
> > Addr From : fffff80758052000 to Addr To : fffff80758052020 | ReadSize : 20
> > ```
> 
> Yes, it's correct; we should have 3 page accesses in this case. We're accessing memory on 3 different pages.

Yes. Actually 3 pages need to be read. I thought wrong before.

**Comment by gmh5225** [comment]
I think I should close this PR and wait for your fix :)

**Comment by SinaKarvandi** [comment]
I made the very first patch. But not yet tested it.

https://github.com/HyperDbg/HyperDbg/commit/a7fc392029d25a4f1a35cef603a5914711227558

By the way, it's one of the critical functions of HyperDbg. Thanks a lot for reporting this problem. This function is called in almost any functionality of HyperDbg.

**Comment by gmh5225** [comment]
> 
you are welcome. 
nice work. I will test it.

**Pull request closed without merging**
