### PR TITLE
auto generated CMakeLists.txt files for all projects

### PR DESCRIPTION
**Pull request by ddkwork**
# Description

Please include a summary of the change and which issue is fixed. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant, or add anything you think would be helpful.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Please ONLY submit your pull request to the "Dev" branch, pull requests to the "Master" branch are not accepted!**

### CODE REVIEW

**Comment by ddkwork** [comment]
我没有pr这个仓库，你自己加上去即可

D:\fork\HyperDbg\hyperdbg\dependencies\pdbex\Source\CMakeLists.txt
```go
set(SourceFiles
    "HyperDbgIntegration.cpp"
    "main.cpp"
    "PDB.cpp"
    "PDBExtractor.cpp"
    "PDBHeaderReconstructor.cpp"
    "HyperDbgExport.h"
    "HyperDbgGlobals.h"
    "PDB.h"
    "PDBCallback.h"
    "PDBExtractor.h"
    "PDBHeaderReconstructor.h"
    "PDBReconstructorBase.h"
    "PDBSymbolSorterAlphabetical.h"
    "PDBSymbolSorterBase.h"
    "PDBSymbolVisitorBase.h"
    "PDBSymbolVisitor.h"
    "PDBSymbolSorter.h"
    "UdtFieldDefinition.h"
    "UdtFieldDefinitionBase.h"
)
include_directories( "DIA SDK/include" )
add_library(pdbex SHARED ${SourceFiles})

```

**Comment by SinaKarvandi** [comment]
Could you please make a new PR (this one seems to break CI/CD since the 'pdbex' submodule is modified).
image

Other than that, in order to preserve the convention, would you please change the `mergeDlls` folder to `merge-dlls`? and also please do not put image files since it's not okay in the git history:
image

And of course, don't touch submodules (pdbex). 🙂 
If possible please close this Pull Request and create a new one (do not update this, close it and create a new one) to be merged to the 'dev' branch. Thank you.

-------------------------------------------------------

您能否创建一个新的 PR（由于“pdbex”子模块已被修改，因此这个 PR 似乎会破坏 CI/CD）。
image

除此之外，为了保留惯例，您能否将“mergeDlls”文件夹更改为“merge-dlls”？另外，请不要放置图像文件，因为 git 历史记录中不允许这样：
image

当然，不要触碰子模块 (pdbex)。🙂
如果可能，请关闭此 Pull 请求并创建一个新的请求（不要更新此请求，关闭它并创建一个新的请求）以合并到“dev”分支。谢谢。

**Comment by ddkwork** [comment]
pdbex需要同步支持cmake，它需要被升级，我之前也说了这一点。现在网络很不稳定，我想您可以先备份子模块，然后手动加入我的pr吗？

**Comment by ddkwork** [comment]
你可以随意命名它，我现在网络很糟糕，访问github非常困难



---Original---
From: "Sina ***@***.***&gt;
Date: Mon, Jul 1, 2024 11:58 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HyperDbg/HyperDbg] auto generated CMakeLists.txt files for allprojects (PR #407)




 
Could you please make a new PR (this one seems to break CI/CD since the 'pdbex' submodule is modified).
 image.png (view on web)
 
Other than that, in order to preserve the convention, would you please change the mergeDlls folder to merge-dlls? and also please do not put image files since it's not okay in the git history:
 image.png (view on web)
 
And of course, don't touch submodules (pdbex). 🙂
 If possible please close this Pull Request and create a new one (do not update this, close it and create a new one) to be merged to the 'dev' branch. Thank you.
 
 
您能否创建一个新的 PR（由于“pdbex”子模块已被修改，因此这个 PR 似乎会破坏 CI/CD）。
 image.png (view on web)
 
除此之外，为了保留惯例，您能否将“mergeDlls”文件夹更改为“merge-dlls”？另外，请不要放置图像文件，因为 git 历史记录中不允许这样：
 image.png (view on web)
 
当然，不要触碰子模块 (pdbex)。🙂
 如果可能，请关闭此 Pull 请求并创建一个新的请求（不要更新此请求，关闭它并创建一个新的请求）以合并到“dev”分支。谢谢。

**Comment by SinaKarvandi** [comment]
I can manually add it by it's better to be added by you since you did the job. You can make a PR later when your network is stable. About pdbex, you can create a PR in the pdbex repo and I'll update the submodule in the main repo.

https://github.com/HyperDbg/pdbex


-------------------------

我可以手动添加，但最好由你添加，因为你做了这项工作。你可以在网络稳定后再创建 PR。关于 pdbex，你可以在 pdbex repo 中创建 PR，我会在主 repo 中更新子模块。

https://github.com/HyperDbg/pdbex

**Comment by ddkwork** [comment]
oh my gad，you do.
我只所以一直能登录GitHub是因为使用了GitHub mobile，pc上我没有办法稳定的访问。

**Pull request closed without merging**
