### PR TITLE
Dev cmake

### PR DESCRIPTION
**Pull request by ddkwork**
# Description

Please include a summary of the change and which issue is fixed. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant, or add anything you think would be helpful.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Please ONLY submit your pull request to the "Dev" branch, pull requests to the "Master" branch are not accepted!**

### CODE REVIEW

**Comment by ddkwork** [comment]
ab34a62272e70b21f41eff2cd55e1b06

For hyperdbg you need to fix warnings and errors, which you are familiar with.

**Comment by SinaKarvandi** [comment]
Hi,
Any instructions on how to use it? Also why there is a sample driver? Could you remove that sample driver since it's not really used in HyperDbg, it's better to keep the HyperDbg repo as clean as possible. Other than that, could you change the FindWDK folder to something more meaningful? It doesn't follow HyperDbg's folder naming convention (every folder name is lowercase separated by a '-' character). Please fix them before merging. Thanks

嗨，
有关于如何使用它的说明吗？还有为什么有一个示例驱动程序？您可以删除该示例驱动程序吗？因为它在 HyperDbg 中并没有真正使用，最好尽可能保持 HyperDbg 存储库的干净。除此之外，您可以将 FindWDK 文件夹更改为更有意义的内容吗？它不符合 HyperDbg 的文件夹命名约定（每个文件夹名称都是小写的，以“-”字符分隔）。请在合并之前修复它们。谢谢

**Comment by ddkwork** [comment]
那个可以删除，它只是为了让你熟悉findwdk而已，我觉得剩下的编译警告和错误应该由您来修复cmake，我应该把时间花在gui仓库上



---Original---
From: "Sina ***@***.***&gt;
Date: Sun, Jun 30, 2024 20:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HyperDbg/HyperDbg] Dev cmake (PR #404)




 
Hi,
 Any instructions on how to use it? Also why there is a sample driver? Could you remove that sample driver since it's not really used in HyperDbg, it's better to keep the HyperDbg repo as clean as possible. Other than that, could you change the FindWDK folder to something more meaningful? It doesn't follow HyperDbg's folder naming convention (every folder name is lowercase separated by a '-' character). Please fix them before merging. Thanks
 
嗨，
 有关于如何使用它的说明吗？还有为什么有一个示例驱动程序？您可以删除该示例驱动程序吗？因为它在 HyperDbg 中并没有真正使用，最好尽可能保持 HyperDbg 存储库的干净。除此之外，您可以将 FindWDK 文件夹更改为更有意义的内容吗？它不符合 HyperDbg 的文件夹命名约定（每个文件夹名称都是小写的，以“-”字符分隔）。请在合并之前修复它们。谢谢

**Comment by SinaKarvandi** [comment]
So is it working now? Or need to be completed later? Do you have any examples of how we can use it? Also, would you please change the FindWDK to something more meaningful following the naming convention (every folder name is lowercase separated by a '-' character)?

那么它现在可以正常工作了吗？还是需要稍后完成？您有任何关于如何使用它的示例吗？另外，您能否按照命名约定将 FindWDK 更改为更有意义的名称（每个文件夹名称都是小写的，并用“-”字符分隔）？

**Comment by ddkwork** [comment]
我已删除了文件夹，因为我们只需要cmake文件即可，它还在处理中，我正在找我以前构建成功的记录和资料。
使用方法如下:
clion打开工程，它会弹出编译器配置，选中vs2022，把它网上调，把gcc删除或者往下移动，此时点击工具栏构建按钮即可。


不使用ide的情况下直接cmake -b xxx 我忘记命令了。不过使用cmake主要是为了使用ide，对于我而言。



---Original---
From: "Sina ***@***.***&gt;
Date: Sun, Jun 30, 2024 21:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HyperDbg/HyperDbg] Dev cmake (PR #404)




 
So is it working now? Or need to be completed later? Do you have any examples of how we can use it? Also, would you please change the FindWDK to something more meaningful following the naming convention (every folder name is lowercase separated by a '-' character)?
 
那么它现在可以正常工作了吗？还是需要稍后完成？您有任何关于如何使用它的示例吗？另外，您能否按照命名约定将 FindWDK 更改为更有意义的名称（每个文件夹名称都是小写的，并用“-”字符分隔）？

**Comment by ddkwork** [comment]
FindWDK是个仓库名称，就像zydis一样，改名不是个好主意，如果作为子模块的话，只是为了简化，我直接删除了改目录



---Original---
From: "Sina ***@***.***&gt;
Date: Sun, Jun 30, 2024 21:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HyperDbg/HyperDbg] Dev cmake (PR #404)




 
So is it working now? Or need to be completed later? Do you have any examples of how we can use it? Also, would you please change the FindWDK to something more meaningful following the naming convention (every folder name is lowercase separated by a '-' character)?
 
那么它现在可以正常工作了吗？还是需要稍后完成？您有任何关于如何使用它的示例吗？另外，您能否按照命名约定将 FindWDK 更改为更有意义的名称（每个文件夹名称都是小写的，并用“-”字符分隔）？

**Comment by ddkwork** [comment]
我已经找到了之前的方式，并用代码为所有工程自动生成了cmakelist。

see
https://github.com/HyperDbg/HyperDbg/pull/407

**Comment by SinaKarvandi** [comment]
That's great. Please create a new PR and send it. Thank you for all of your efforts for the HyperDbg and the reversing community.
--------------------------
太棒了。请创建一个新的 PR 并发送。感谢您为 HyperDbg 和逆向社区做出的所有努力。

**Pull request merged**
